### ISSUE TITLE
Please fix icon

### ISSUE THREAD

**Issue by stoecker** [species/josm-preset-traffic_sign_direction#3]
The icon for this style does no longer exists under that name. Could you please use another one or fix the path? This issue causes warnings in the JOSM server backend.

If not fixed the style will be disabled in JOSM wiki until fixed.

**Comment by species** [comment]
fixed in aa6a789, used new svg variant from vehicle/restriction/give_way.svg.

Thanks for the hint!

**Comment by stoecker** [comment]
Thanks a lot for freeing my mail inbox :-)

**Comment by stoecker** [comment]
Ah. Still get mails. You forgot the "styles/standard/" before. That's added inside of JOSM :-)

**Comment by species** [comment]
Strange - it worked this way, copied it straight out of the JOSM default mapcss style?

Looks like this is also a bug in your JOSM server backend...

Anyway, changed as requested in a180459b7f109342eeec38dc05dd4a1a368db94f.

**Comment by stoecker** [comment]
Can be that there is an error in backend. As it tries to simulate JOSM behaviour for the embedded icons - and simulations are never like the original :-) It really worked without the additional path?

Anyway so it's easier for me...

**Comment by species** [comment]
Yes, most of the icons in the default mapcss don't use "styles/standard/" any longer.
